DB_root_user: "root"
DB_root_pass: "1q2w3e4r5t"
remove_installed: "1"
DB_host: "localhost"
DB_name: "zabbixdb"
DB_user: "zabbixuser"
DB_pass: "1q2w3e"
postgresql_rpm_6: "https://yum.postgresql.org/9.5/redhat/rhel-6.9-x86_64/pgdg-centos95-9.5-2.noarch.rpm"
postgresql_rpm_7: "https://yum.postgresql.org/9.5/redhat/rhel-7.3-x86_64/pgdg-centos95-9.5-2.noarch.rpm"
repmgr_rpm_6: "https://yum.postgresql.org/9.5/redhat/rhel-6.9-x86_64/repmgr95-3.3.1-1.hel6.x86_64.rpm"
repmgr_rpm_7: "https://yum.postgresql.org/9.5/redhat/rhel-7.3-x86_64/repmgr95-3.3.1-1.rhel7.x86_64.rpm"
zabbix_rpm_6: "http://repo.zabbix.com/zabbix/3.0/rhel/6/x86_64/zabbix-release-3.0-1.el6.noarch.rpm"
zabbix_rpm_7: "http://repo.zabbix.com/zabbix/3.0/rhel/7/x86_64/zabbix-release-3.0-1.el7.noarch.rpm"
php_rpm_6: "https://mirror.webtatic.com/yum/el6/latest.rpm"
php_rpm_7: "https://mirror.webtatic.com/yum/el7/webtatic-release.rpm"
